[package]
name = "tui"
version = "0.1.0"
edition = "2024"

[dependencies]
core = { version = "0.1.0", path = "../core" }
anyhow.workspace = true
http-body-util = "0.1.3"
hyper = { version = "1.6.0", features = ["full"] }
hyper-util = { version = "0.1.14", features = ["full"] }
rustls = { version = "0.23.28", features = ["ring", "std"] }
thiserror.workspace = true
tokio = { version = "1.45.1", features = ["full"] }
