[package]
name = "tui"
version = "0.1.0"
edition = "2024"

[dependencies]
charlotte = { version = "0.1.0", path = "../charlotte" }
anyhow.workspace = true
thiserror.workspace = true
tokio = { version = "1.45.1", features = ["full"] }
